### PR TITLE
crypto: Updated nrf_oberon to version 3.0.2

### PR DESCRIPTION
**Pull request by tejlmand**
Adding nrf_oberon v3.0.2
Removing nrf_oberon v3.0.0

Signed-off-by: Torsten Rasmussen <Torsten.Rasmussen@nordicsemi.no>

### CODE REVIEW

**Comment by osaether** [comment]
The header files are not updated. Are they identical to those in v3.0.0?

**Comment by osaether** [comment]
CHANGELOG.rst still mention 3.0.0

**Comment by osaether** [comment]
ocrypto_sha1.h is missing.

**Comment by tejlmand** [comment]
> The header files are not updated. Are they identical to those in v3.0.0?

yes, except for the missing header which you also have noticed.

**Comment by lemrey** [comment]
Please remember to open a matching PR to -nrf to make sure we run CI on this, before merging.

**Comment by tejlmand** [comment]
> Please remember to open a matching PR to -nrf to make sure we run CI on this, before merging.

That was put up two days ago together with this PR: 
https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/1323

**Pull request merged**
