### PR TITLE
nfc: T2T library documentation: removed obsolete statements

### PR DESCRIPTION
**Pull request by grochu**
Removed outdated and misleading statements in the API documentation.

Fixing: NCSDK-1859

### CODE REVIEW

**Comment by grochu** [comment]
@b-gent could you please review?

**Comment by kapi-no** [comment]
@carlescufi, could you merge it?

**Comment by grochu** [comment]
@lemrey could you merge this PR?

**Comment by grochu** [comment]
@b-gent could you please re-check? The upmerge was done so I will be able to merge this PR finally.

**Comment by b-gent** [comment]
> @b-gent could you please re-check?

still good

**Pull request merged**
