### PR TITLE
bsdlib: version 0.7.2

### PR DESCRIPTION
**Pull request by tommi-m**
Library version: 9405fb2133f40f01ac743db2203a8438929631b5

- Added support in bsd_init() to disable tracing and define
  memory size and location.

Corresponding manifest update: https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/2207

Signed-off-by: Tommi Mammela <tommi.mammela@nordicsemi.no>

### CODE REVIEW

**Comment by rlubos** [comment]
@eibe85 I have no clue why can't I add you to the reviewers list, please consider yourself "review requested" :)

**Comment by rlubos** [comment]
@tommi-m 0.7.1 was just merged, please rebase.

**Comment by eibe85** [comment]
I think I can be invited to review now. Not certain I can I can invite myself to do it :)

**Comment by rlubos** [comment]
Indeed you can. Do you know what happened? I had similar problem with some other person, but in fw-nrfconnect-nrf repo. Some GH issues?

**Comment by eibe85** [comment]
@rlubos I just did not have two factor auth enabled when the deadline was out and needed to be invited back in to the Nordic repos as contributor.

**Comment by tommi-m** [comment]
> 
> 
> Ran BSDlib tests. And did not find any problems when running with nrf PR2207 but I don't understand how I as a user should chose address or size for bsd_init

This is only a temporary phase. The final stage is to use address and size from partition manager when it's ready.

**Comment by lemrey** [comment]
Hi @eibe85, the defaults are in the `bsd_platform.h` file, we have added a reference to them next to the `bsd_init_params_t` structure so that it is clearer.

**Comment by eibe85** [comment]
@lemrey ok good. I swa it in the PR but think it would have been more difficult to find it without the diff in the PR. There is no code change I hope, no reason to rerun tests?

**Comment by rlubos** [comment]
@b-gent Any concerns regarding the changelog? We'd like to push this PR forward.

**Comment by rlubos** [comment]
Seems that only CI is blocking us right now?

**Comment by tommi-m** [comment]
> 
> 
> Seems that only CI is blocking us right now?

**Comment by tommi-m** [comment]
@rlubos I think everything is ok now.

**Comment by tommi-m** [comment]
Seems that when running CI manually it's green but when run automatically it fails

**Comment by rlubos** [comment]
The problem seems to be this commit: https://github.com/NordicPlayground/nrfxlib/commit/a9c1f80636ceeeb678465959986ba831ff4cdf31, which IMO got merged too early. It's related to the upmerge, but the upmerge is not ready to be merged yet. I'm afraid we're stuck.

@joerchan @ioannisg Shall we revert it or wait for the upmerge to complete? How far are we from completing the upmerge?

**Comment by joerchan** [comment]
> The problem seems to be this commit: [a9c1f80](https://github.com/NordicPlayground/nrfxlib/commit/a9c1f80636ceeeb678465959986ba831ff4cdf31), which IMO got merged too early. It's related to the upmerge, but the upmerge is not ready to be merged yet. I'm afraid we're stuck.
> 
> @joerchan @ioannisg Shall we revert it or wait for the upmerge to complete? How far are we from completing the upmerge?

@rlubos Sorry about this. I have reverted the change, as you say it was merged too early.

**Comment by rlubos** [comment]
@tommi-m The fault commit was reverted, could you please rebase?

**Comment by tommi-m** [comment]
Now we have all green

**Pull request merged**
