### PR TITLE
bluetooth: controller: Remove version and family from lib name

### PR DESCRIPTION
**Pull request by rugeGerritsen**
The ble controller library is identified by the nrfxlib revision
and the revision obtained by ble_controller_build_revision_get()

Signed-off-by: Rubin Gerritsen <Rubin.Gerritsen@nordicsemi.no>

### CODE REVIEW

**Comment by rugeGerritsen** [comment]
@joerchan: Can you review this?

**Comment by joerchan** [comment]
@ruge, this seems fine with me, can you set up a nrf review referencing this pr, so that we can run it in CI?

**Comment by rugeGerritsen** [comment]
> @ruge, this seems fine with me, can you set up a nrf review referencing this pr, so that we can run it in CI?

See https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/1515

**Comment by rugeGerritsen** [comment]
> @ruge, this seems fine with me, can you set up a nrf review referencing this pr, so that we can run it in CI?
> 
> See NordicPlayground/fw-nrfconnect-nrf#1515

CI is now passing

**Pull request merged**
