### PR TITLE
bsdlib: Update BSD library for nrf9160

### PR DESCRIPTION
**Pull request by gbakke**
Library version ae2af83c9c7.

Signed-off-by: Glenn Ruben Bakke <glenn.ruben.bakke@nordicsemi.no>

### CODE REVIEW

**Comment by gbakke** [comment]
Will be rebased when 0.4.0 gets merged.

CC @metc.

**Comment by eibe85** [comment]
It looks like packets larger than 4096 are not handled well now. Previousl thsi has returned ENOMEM but now it is stuck for ever. I think it should return ENOBUFS not ENOMEM though. See https://projecttools.nordicsemi.no/jira/browse/NCSDK-2724

**Comment by eibe85** [comment]
Throughput test looks good now though.

**Comment by lemrey** [comment]
Please update the description with the correct library hash, so there is no doubt as to which is correct the one in the commit or the one in the description.

**Comment by lemrey** [comment]
It wouldn't hurt to start putting the changelog in the commit message, so that it is visible in the git log.

**Comment by rlubos** [comment]
@gbakke Please squash the doc fixes before we merge.

**Comment by lemrey** [comment]
Do not merge yet.

**Comment by gbakke** [comment]
@rlubos , @carlescufi , merge lock released. Can now be merged.

**Comment by carlescufi** [comment]
@gbakke do you have a PR to -nrf with the updated SHA in `west.yml`? I would really like to see CI green there.

**Comment by gbakke** [comment]
@carlescufi , @lemrey will first provide a patch to fw-nrfconnect-zephyr. Then @metc has a PR to nrf updating the hash in https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/1103 to use this library.

**Pull request merged**
