### PR TITLE
bsdlib: bump to version 0.5.1

### PR DESCRIPTION
**Pull request by evenl**
Fixed internal memory issue in GNSS which lead to crash when running for hours

Library version number: 08234ed690e865b6adfbf670519d2010dd0333b7

Manifest update PR: https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/1586

Signed-off-by: Even Falch-Larsen <even.falch-larsen@nordicsemi.no>

### CODE REVIEW

**Comment by evenl** [comment]
Can someone have a look at this PR?

**Comment by rlubos** [comment]
@evenl Aren't we waiting for approval from the test team that this library revision passes all tests needed?

**Comment by magnev** [comment]
Gps module test, and Gps sample test passed

**Comment by JeffLangballe** [comment]
Are there plans to backport this to the v1.1 tag?

**Pull request merged**
