### PR TITLE
nfc: Fix default IRQ priority when ZERO_LATENCY_IRQS are used

### PR DESCRIPTION
**Pull request by thomasstenersen**
Fixes NCSDK-3404 and a small documentation bug.

Signed-off-by: Thomas Stenersen <thomas.stenersen@nordicsemi.no>

### CODE REVIEW

**Comment by thomasstenersen** [comment]
@grochu: This should fix the issue. FYI @qung @shantha-14.

**Comment by joerchan** [comment]
@KAGA164 Could you check this?

**Comment by thomasstenersen** [comment]
It doesn't really have anything to do with the low latency mode. It's just that when `CONFIG_ZERO_LATENCY_IRQS=y`, which the `BT_LL_NRFXLIB` sets, the number of IRQ levels for the kernel is reduced by one. When this config is set and the NFC lib defaults to 6, this assert will fail: https://github.com/zephyrproject-rtos/zephyr/blob/master/arch/arm/core/irq_manage.c#L93

**Comment by grochu** [comment]
Alright I see. Perhaps we should change the way we set the NFCT IRQ priority in general (maybe use the default from DTS?), but that's a topic for another PR.

**Comment by joerchan** [comment]
> Note that @KAGA164 is at the UPF right now and might not be able to review.

Yeah. I think he is not needed. We have enough eyes now.

**Pull request merged**
