### PR TITLE
Update lib oberon deps

### PR DESCRIPTION
**Pull request by gbakke**
Updated library to address API changes introduced in #39.

### CODE REVIEW

**Comment by lemrey** [comment]
We should update the `README` file too, right?

**Comment by gbakke** [comment]
why? Changelog will be updated.

**Comment by lemrey** [comment]
Right, sorry I meant `CHANGELOG` :)

**Comment by gbakke** [comment]
CC @rlubos , @ru-fu

**Comment by gbakke** [comment]
@ru-fu , i'll apply the patches and amend the commit. Thanks.I'll give you an indication when done.

**Comment by gbakke** [comment]
@ru-fu , updated according to patch.

**Comment by rlubos** [comment]
@ru-fu Please re-check at your convenience.

**Pull request merged**
