### PR TITLE
bsdlib: Update BSD library for nrf9160.

### PR DESCRIPTION
**Pull request by gbakke**
Library version 8470d49003d.

Signed-off-by: Glenn Ruben Bakke <glenn.ruben.bakke@nordicsemi.no>

### CODE REVIEW

**Comment by Raane** [comment]
@ru-fu can you have a look at the documentation? We plan to merge this today to make it accessible to developers who would like to start using this.

**Comment by ru-fu** [comment]
I tried to add a commit with doc updates, but don't have permissions to push to your branch.
So here's the diff instead: 
[diff.txt](https://github.com/NordicPlayground/nrfxlib/files/3141969/diff.txt)

**Comment by ru-fu** [comment]
Commit with language review added - please check and squash, if okay. And as mentioned, those changes won't show up in the output.

**Comment by SebastianBoe** [comment]
@Raane : I will await merging this until @ru-fu 's has approved.

**Comment by gbakke** [comment]
Squashed and rebased.

**Comment by SebastianBoe** [comment]
@Raane : I'm sure you know this, but a manifest PR is needed to get this into the release.

**Pull request merged**
