### PR TITLE
nfc: Fix default IRQ priority when ZERO_LATENCY_IRQS are used

### PR DESCRIPTION
**Pull request by joerchan**
Fixes NCSDK-3404 and a small documentation bug.

Signed-off-by: Thomas Stenersen <thomas.stenersen@nordicsemi.no>

### CODE REVIEW

**Comment by joerchan** [comment]
@grochu @thomasstenersen Had to manually backport https://github.com/NordicPlayground/nrfxlib/pull/95 because of the branch permissions.

**Comment by tejlmand** [comment]
I don't see a corresponding PR in https://github.com/NordicPlayground/fw-nrfconnect-nrf
which means this PR has been merged WITHOUT CI testing.

Please remember to create a corresponding PR i https://github.com/NordicPlayground/fw-nrfconnect-nrf with an updated `west.yml`

**Comment by joerchan** [comment]
> I don't see a corresponding PR in https://github.com/NordicPlayground/fw-nrfconnect-nrf
> which means this PR has been merged WITHOUT CI testing.
> 
> Please remember to create a corresponding PR i https://github.com/NordicPlayground/fw-nrfconnect-nrf with an updated `west.yml`

Ups. Added one now:
https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/1418

**Comment by carlescufi** [comment]
> I don't see a corresponding PR in https://github.com/NordicPlayground/fw-nrfconnect-nrf
> which means this PR has been merged WITHOUT CI testing.
> 
> Please remember to create a corresponding PR i https://github.com/NordicPlayground/fw-nrfconnect-nrf with an updated `west.yml`

Thanks @tejlmand fro bringing this up. It's unfortunate that we cannot enforce this for now, but I think it'd be doable with a bot.

**Pull request merged**
